import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

export const LANGUAGE_OPTIONS = [
  { code: 'en', name: 'English' }, { code: 'ta', name: 'தமிழ்' },
  { code: 'hi', name: 'हिन्दी' }, { code: 'te', name: 'తెలుగు' },
  { code: 'kn', name: 'ಕನ್ನಡ' }, { code: 'ml', name: 'മലയാളം' },
  { code: 'bn', name: 'বাংলা' }, { code: 'mr', name: 'मराठी' },
]

const en = {
  language: 'Language', screening: 'Document Screening', dashboard: 'Dashboard', trustedRegistry: 'Trusted Registry', watchlist: 'Watchlist', caseReview: 'Case Review', auditTrail: 'Audit Trail', systemStatus: 'System Status',
  identityScreening: 'Identity Screening', systemsOperational: 'Systems Operational', serviceUnavailable: 'Service Unavailable', resetDemo: 'Reset Demo', resetting: 'Resetting…',
  identityDocument: 'Identity Document', applicantSelfie: 'Applicant Selfie', documentSubtitle: "Passport · National ID · Visa · Driver's License", selfieSubtitle: 'Live frontal portrait — clear, unobstructed',
  uploadIdentityDocument: 'Upload Identity Document', dragDrop: 'Drag and drop', clickToUpload: 'Click to upload', browseFile: 'Browse file', supportedFormats: 'JPEG, PNG · Up to 15 MB', startAnalysis: 'Start Analysis', startScreening: 'Start Identity Screening', processing: 'Processing Screening Pipeline…',
  replaceImage: 'Replace image', removeImage: 'Remove image', attached: 'Attached', unsupportedFile: 'Unsupported File', unsupportedFormat: 'Unsupported format. Use JPEG or PNG.', fileTooLarge: 'File exceeds 15 MB limit.',
  openCamera: 'Open Camera', captureSelfie: 'Capture Selfie', retake: 'Retake', uploadPhoto: 'Upload Photo', cameraPermission: 'Camera Permission Required',
  newScreening: 'New Screening', verificationResult: 'Verification Result', riskScore: 'Risk Score', riskAssessment: 'Risk Assessment', lowRisk: 'Low Risk', mediumRisk: 'Medium Risk', highRisk: 'High Risk', manualReviewRequired: 'Manual Review Required', secondaryInspection: 'Secondary Inspection Recommended', clear: 'Clear', manualReview: 'Manual Review', recheck: 'Recheck', scanAnother: 'Scan Another Document',
  extractedDocumentInformation: 'Extracted Document Information', fullName: 'Name', documentType: 'Document Type', documentNumber: 'Document Number', nationality: 'Nationality', dateOfBirth: 'Date of Birth', expiryDate: 'Expiry Date', issueDate: 'Issue Date', sex: 'Sex', issuingAuthority: 'Issuing Authority', institution: 'Institution / Organization', notAvailable: 'Not available',
  documentIntegrity: 'Document Integrity', noSignificantAnomaly: 'No Significant Anomaly Detected', suspicious: 'Suspicious', possibleManipulation: 'Possible Manipulation Detected', faceVerification: 'Face Verification', faceMatch: 'Face Match', faceSimilarity: 'Face Similarity', match: 'Match', mismatch: 'Mismatch',
  riskFactors: 'Risk Assessment Factors', reasons: 'Reasons', recommendation: 'Recommendation', detectedIssues: 'Detected Issues', report: 'Document Integrity Report', analysisFailed: 'Analysis Failed', pleaseTryAgain: 'Please try again', systemNotice: 'Screening System Notice', dismiss: 'Dismiss',
  readingDocument: 'Reading Document', extractingInformation: 'Extracting Information', checkingIntegrity: 'Checking Document Integrity', analysingIdentity: 'Analysing Identity', comparingFace: 'Comparing Face', calculatingRisk: 'Calculating Risk', generatingReport: 'Generating Report',
  lowDirective: 'Routine Review Recommended', reviewDirective: 'Secondary Inspection Recommended', highDirective: 'Immediate Officer Review Required',
  lowDetail: 'All biometric and document checks satisfied automated screening thresholds. Proceed with standard clearance.', reviewDetail: 'Minor discrepancies or borderline biometric confidence detected. Direct the applicant to secondary screening.', highDetail: 'Critical anomalies detected. Hold the applicant and escalate immediately.',
  reason_name_region_anomaly: 'Possible modification detected around the Name field.', reason_visible_mrz_data_mismatch: 'Encoded information does not match visible text.', reason_face_mismatch: 'Face mismatch detected between document portrait and selfie.', reason_low_image_quality: 'Low image quality may affect verification.', reason_typography_inconsistency: 'Typography inconsistency detected in the document.',
}

const localized = {
  ta: { language:'மொழி', screening:'ஆவணச் சரிபார்ப்பு', dashboard:'முகப்பு', watchlist:'கண்காணிப்பு பட்டியல்', identityScreening:'அடையாளச் சரிபார்ப்பு', systemsOperational:'அமைப்புகள் செயல்பாட்டில் உள்ளன', serviceUnavailable:'சேவை கிடைக்கவில்லை', resetDemo:'டெமோவை மீட்டமை', identityDocument:'அடையாள ஆவணம்', applicantSelfie:'விண்ணப்பதாரர் செல்ஃபி', uploadIdentityDocument:'அடையாள ஆவணத்தைப் பதிவேற்றவும்', dragDrop:'இழுத்து விடவும்', clickToUpload:'பதிவேற்ற கிளிக் செய்யவும்', browseFile:'கோப்பைத் தேர்ந்தெடுக்கவும்', supportedFormats:'JPEG, PNG · 15 MB வரை', startAnalysis:'பகுப்பாய்வைத் தொடங்கவும்', startScreening:'அடையாளச் சரிபார்ப்பைத் தொடங்கவும்', processing:'சரிபார்ப்பு நடைபெறுகிறது…', newScreening:'புதிய சரிபார்ப்பு', verificationResult:'சரிபார்ப்பு முடிவு', riskScore:'அபாய மதிப்பெண்', riskAssessment:'அபாய மதிப்பீடு', lowRisk:'குறைந்த அபாயம்', mediumRisk:'நடுத்தர அபாயம்', highRisk:'அதிக அபாயம்', manualReviewRequired:'கைமுறை சரிபார்ப்பு தேவை', secondaryInspection:'கூடுதல் சரிபார்ப்பு பரிந்துரைக்கப்படுகிறது', extractedDocumentInformation:'பெறப்பட்ட ஆவணத் தகவல்', fullName:'பெயர்', documentType:'ஆவண வகை', documentNumber:'ஆவண எண்', nationality:'தேசியம்', dateOfBirth:'பிறந்த தேதி', expiryDate:'காலாவதி தேதி', issueDate:'வழங்கிய தேதி', notAvailable:'கிடைக்கவில்லை', documentIntegrity:'ஆவண ஒருமைப்பாடு', noSignificantAnomaly:'முக்கியமான முரண்பாடு இல்லை', suspicious:'சந்தேகத்திற்குரியது', possibleManipulation:'சாத்தியமான மாற்றம் கண்டறியப்பட்டது', faceVerification:'முகச் சரிபார்ப்பு', faceMatch:'முகப் பொருத்தம்', faceSimilarity:'முக ஒற்றுமை', match:'பொருந்துகிறது', mismatch:'பொருந்தவில்லை', riskFactors:'அபாய மதிப்பீட்டுக் காரணிகள்', reasons:'காரணங்கள்', recommendation:'பரிந்துரை', detectedIssues:'கண்டறியப்பட்ட சிக்கல்கள்', report:'ஆவண ஒருமைப்பாட்டு அறிக்கை', analysisFailed:'பகுப்பாய்வு தோல்வியடைந்தது', pleaseTryAgain:'மீண்டும் முயற்சிக்கவும்', systemNotice:'சரிபார்ப்பு அமைப்பு அறிவிப்பு', dismiss:'மூடு', readingDocument:'ஆவணம் படிக்கப்படுகிறது', extractingInformation:'தகவல் பெறப்படுகிறது', checkingIntegrity:'ஆவண ஒருமைப்பாடு சரிபார்க்கப்படுகிறது', analysingIdentity:'அடையாளம் பகுப்பாய்வு செய்யப்படுகிறது', comparingFace:'முகம் ஒப்பிடப்படுகிறது', calculatingRisk:'அபாயம் கணக்கிடப்படுகிறது', generatingReport:'அறிக்கை உருவாக்கப்படுகிறது', lowDirective:'வழக்கமான சரிபார்ப்பு பரிந்துரைக்கப்படுகிறது', reviewDirective:'கூடுதல் சரிபார்ப்பு பரிந்துரைக்கப்படுகிறது', highDirective:'உடனடி அதிகாரி சரிபார்ப்பு தேவை', reason_name_region_anomaly:'பெயர் பகுதியில் சாத்தியமான மாற்றம் கண்டறியப்பட்டது.', reason_visible_mrz_data_mismatch:'குறியாக்கப்பட்ட தகவல் மற்றும் காணப்படும் உரை பொருந்தவில்லை.', reason_face_mismatch:'ஆவணப் படம் மற்றும் செல்ஃபி முகம் பொருந்தவில்லை.', reason_low_image_quality:'குறைந்த படத் தரம் சரிபார்ப்பைப் பாதிக்கலாம்.', reason_typography_inconsistency:'ஆவணத்தில் எழுத்துரு முரண்பாடு கண்டறியப்பட்டது.' },
  hi: { language:'भाषा', screening:'दस्तावेज़ जाँच', dashboard:'डैशबोर्ड', watchlist:'निगरानी सूची', identityScreening:'पहचान जाँच', systemsOperational:'सिस्टम कार्यरत हैं', serviceUnavailable:'सेवा अनुपलब्ध', resetDemo:'डेमो रीसेट करें', identityDocument:'पहचान दस्तावेज़', applicantSelfie:'आवेदक सेल्फी', uploadIdentityDocument:'पहचान दस्तावेज़ अपलोड करें', dragDrop:'खींचें और छोड़ें', clickToUpload:'अपलोड करने के लिए क्लिक करें', browseFile:'फ़ाइल चुनें', supportedFormats:'JPEG, PNG · 15 MB तक', startAnalysis:'विश्लेषण शुरू करें', startScreening:'पहचान जाँच शुरू करें', processing:'जाँच प्रक्रिया चल रही है…', newScreening:'नई जाँच', verificationResult:'सत्यापन परिणाम', riskScore:'जोखिम स्कोर', riskAssessment:'जोखिम मूल्यांकन', lowRisk:'कम जोखिम', mediumRisk:'मध्यम जोखिम', highRisk:'उच्च जोखिम', manualReviewRequired:'मैन्युअल समीक्षा आवश्यक', secondaryInspection:'द्वितीयक निरीक्षण अनुशंसित', extractedDocumentInformation:'निकाली गई दस्तावेज़ जानकारी', fullName:'नाम', documentType:'दस्तावेज़ प्रकार', documentNumber:'दस्तावेज़ संख्या', nationality:'राष्ट्रीयता', dateOfBirth:'जन्म तिथि', expiryDate:'समाप्ति तिथि', issueDate:'जारी करने की तिथि', notAvailable:'उपलब्ध नहीं', documentIntegrity:'दस्तावेज़ अखंडता', noSignificantAnomaly:'कोई महत्वपूर्ण विसंगति नहीं मिली', suspicious:'संदिग्ध', possibleManipulation:'संभावित हेरफेर पाया गया', faceVerification:'चेहरा सत्यापन', faceMatch:'चेहरा मिलान', faceSimilarity:'चेहरा समानता', match:'मिलान', mismatch:'बेमेल', riskFactors:'जोखिम मूल्यांकन कारक', reasons:'कारण', recommendation:'अनुशंसा', detectedIssues:'पता चली समस्याएँ', report:'दस्तावेज़ अखंडता रिपोर्ट', analysisFailed:'विश्लेषण विफल', pleaseTryAgain:'कृपया पुनः प्रयास करें', systemNotice:'स्क्रीनिंग सिस्टम सूचना', dismiss:'बंद करें', readingDocument:'दस्तावेज़ पढ़ा जा रहा है', extractingInformation:'जानकारी निकाली जा रही है', checkingIntegrity:'दस्तावेज़ अखंडता जाँची जा रही है', analysingIdentity:'पहचान का विश्लेषण हो रहा है', comparingFace:'चेहरे की तुलना हो रही है', calculatingRisk:'जोखिम की गणना हो रही है', generatingReport:'रिपोर्ट बनाई जा रही है', lowDirective:'सामान्य समीक्षा अनुशंसित', reviewDirective:'द्वितीयक निरीक्षण अनुशंसित', highDirective:'तत्काल अधिकारी समीक्षा आवश्यक', reason_name_region_anomaly:'नाम वाले क्षेत्र में संभावित बदलाव पाया गया है।', reason_visible_mrz_data_mismatch:'एन्कोड की गई जानकारी दृश्य पाठ से मेल नहीं खाती।', reason_face_mismatch:'दस्तावेज़ चित्र और सेल्फी के बीच चेहरा बेमेल पाया गया।', reason_low_image_quality:'कम छवि गुणवत्ता सत्यापन को प्रभावित कर सकती है।', reason_typography_inconsistency:'दस्तावेज़ में टाइपोग्राफी असंगति पाई गई।' },
  te: { language:'భాష', screening:'పత్ర పరిశీలన', identityScreening:'గుర్తింపు పరిశీలన', identityDocument:'గుర్తింపు పత్రం', applicantSelfie:'దరఖాస్తుదారు సెల్ఫీ', uploadIdentityDocument:'గుర్తింపు పత్రాన్ని అప్‌లోడ్ చేయండి', dragDrop:'లాగి వదలండి', clickToUpload:'అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి', browseFile:'ఫైల్ ఎంచుకోండి', startAnalysis:'విశ్లేషణ ప్రారంభించండి', startScreening:'గుర్తింపు పరిశీలన ప్రారంభించండి', processing:'పరిశీలన జరుగుతోంది…', newScreening:'కొత్త పరిశీలన', verificationResult:'ధృవీకరణ ఫలితం', riskScore:'ప్రమాద స్కోరు', riskAssessment:'ప్రమాద అంచనా', lowRisk:'తక్కువ ప్రమాదం', mediumRisk:'మధ్యస్థ ప్రమాదం', highRisk:'అధిక ప్రమాదం', manualReviewRequired:'మాన్యువల్ సమీక్ష అవసరం', secondaryInspection:'ద్వితీయ తనిఖీ సిఫార్సు చేయబడింది', extractedDocumentInformation:'సేకరించిన పత్ర సమాచారం', fullName:'పేరు', documentType:'పత్ర రకం', documentNumber:'పత్ర సంఖ్య', nationality:'జాతీయత', dateOfBirth:'పుట్టిన తేదీ', expiryDate:'గడువు తేదీ', issueDate:'జారీ తేదీ', notAvailable:'అందుబాటులో లేదు', documentIntegrity:'పత్ర సమగ్రత', faceVerification:'ముఖ ధృవీకరణ', faceMatch:'ముఖ సరిపోలిక', match:'సరిపోలింది', mismatch:'సరిపోలలేదు', reasons:'కారణాలు', recommendation:'సిఫార్సు', readingDocument:'పత్రం చదువుతోంది', extractingInformation:'సమాచారం సేకరిస్తోంది', checkingIntegrity:'పత్ర సమగ్రతను తనిఖీ చేస్తోంది', comparingFace:'ముఖాన్ని పోలుస్తోంది', calculatingRisk:'ప్రమాదాన్ని లెక్కిస్తోంది', generatingReport:'నివేదిక తయారవుతోంది', reason_name_region_anomaly:'పేరు ప్రాంతంలో మార్పు ఉండవచ్చు.', reason_visible_mrz_data_mismatch:'ఎన్‌కోడ్ చేసిన సమాచారం కనిపించే పాఠ్యంతో సరిపోలలేదు.', reason_face_mismatch:'పత్రంలోని చిత్రం మరియు సెల్ఫీ మధ్య ముఖం సరిపోలలేదు.', reason_low_image_quality:'తక్కువ చిత్ర నాణ్యత ధృవీకరణను ప్రభావితం చేయవచ్చు.', reason_typography_inconsistency:'పత్రంలో అక్షరరూప అసంగతి గుర్తించబడింది.' },
  kn: { language:'ಭಾಷೆ', screening:'ದಾಖಲೆ ಪರಿಶೀಲನೆ', identityScreening:'ಗುರುತು ಪರಿಶೀಲನೆ', identityDocument:'ಗುರುತಿನ ದಾಖಲೆ', applicantSelfie:'ಅರ್ಜಿದಾರರ ಸೆಲ್ಫಿ', uploadIdentityDocument:'ಗುರುತಿನ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', dragDrop:'ಎಳೆದು ಬಿಡಿ', clickToUpload:'ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ', browseFile:'ಕಡತ ಆಯ್ಕೆ ಮಾಡಿ', startAnalysis:'ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ', startScreening:'ಗುರುತು ಪರಿಶೀಲನೆ ಪ್ರಾರಂಭಿಸಿ', processing:'ಪರಿಶೀಲನೆ ನಡೆಯುತ್ತಿದೆ…', newScreening:'ಹೊಸ ಪರಿಶೀಲನೆ', verificationResult:'ಪರಿಶೀಲನೆ ಫಲಿತಾಂಶ', riskScore:'ಅಪಾಯ ಅಂಕ', riskAssessment:'ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ', lowRisk:'ಕಡಿಮೆ ಅಪಾಯ', mediumRisk:'ಮಧ್ಯಮ ಅಪಾಯ', highRisk:'ಹೆಚ್ಚಿನ ಅಪಾಯ', manualReviewRequired:'ಕೈಯಾರೆ ಪರಿಶೀಲನೆ ಅಗತ್ಯ', secondaryInspection:'ದ್ವಿತೀಯ ಪರಿಶೀಲನೆ ಶಿಫಾರಸು', extractedDocumentInformation:'ಪಡೆಯಲಾದ ದಾಖಲೆ ಮಾಹಿತಿ', fullName:'ಹೆಸರು', documentType:'ದಾಖಲೆ ಪ್ರಕಾರ', documentNumber:'ದಾಖಲೆ ಸಂಖ್ಯೆ', nationality:'ರಾಷ್ಟ್ರೀಯತೆ', dateOfBirth:'ಜನ್ಮ ದಿನಾಂಕ', expiryDate:'ಮುಕ್ತಾಯ ದಿನಾಂಕ', notAvailable:'ಲಭ್ಯವಿಲ್ಲ', documentIntegrity:'ದಾಖಲೆ ಸಮಗ್ರತೆ', faceVerification:'ಮುಖ ಪರಿಶೀಲನೆ', faceMatch:'ಮುಖ ಹೊಂದಾಣಿಕೆ', match:'ಹೊಂದಾಣಿಕೆ', mismatch:'ಹೊಂದಿಕೆಯಾಗಿಲ್ಲ', reasons:'ಕಾರಣಗಳು', recommendation:'ಶಿಫಾರಸು', reason_name_region_anomaly:'ಹೆಸರು ಕ್ಷೇತ್ರದ ಸುತ್ತ ಸಂಭವನೀಯ ಬದಲಾವಣೆ ಪತ್ತೆಯಾಗಿದೆ.', reason_visible_mrz_data_mismatch:'ಸಂಕೇತಿತ ಮಾಹಿತಿ ಗೋಚರ ಪಠ್ಯಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ.', reason_face_mismatch:'ದಾಖಲೆ ಚಿತ್ರ ಮತ್ತು ಸೆಲ್ಫಿ ನಡುವೆ ಮುಖ ಹೊಂದಿಕೆಯಾಗಿಲ್ಲ.', reason_low_image_quality:'ಕಡಿಮೆ ಚಿತ್ರ ಗುಣಮಟ್ಟವು ಪರಿಶೀಲನೆ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರಬಹುದು.', reason_typography_inconsistency:'ದಾಖಲೆಯಲ್ಲಿ ಅಕ್ಷರಶೈಲಿ ಅಸಂಗತಿ ಪತ್ತೆಯಾಗಿದೆ.' },
  ml: { language:'ഭാഷ', screening:'രേഖാ പരിശോധന', identityScreening:'തിരിച്ചറിയൽ പരിശോധന', identityDocument:'തിരിച്ചറിയൽ രേഖ', applicantSelfie:'അപേക്ഷകന്റെ സെൽഫി', uploadIdentityDocument:'തിരിച്ചറിയൽ രേഖ അപ്‌ലോഡ് ചെയ്യുക', dragDrop:'വലിച്ചിടുക', clickToUpload:'അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക', browseFile:'ഫയൽ തിരഞ്ഞെടുക്കുക', startAnalysis:'വിശകലനം ആരംഭിക്കുക', startScreening:'തിരിച്ചറിയൽ പരിശോധന ആരംഭിക്കുക', processing:'പരിശോധന നടക്കുന്നു…', newScreening:'പുതിയ പരിശോധന', verificationResult:'സ്ഥിരീകരണ ഫലം', riskScore:'അപകട സ്കോർ', riskAssessment:'അപകട വിലയിരുത്തൽ', lowRisk:'കുറഞ്ഞ അപകടം', mediumRisk:'ഇടത്തരം അപകടം', highRisk:'ഉയർന്ന അപകടം', manualReviewRequired:'മാനുവൽ പരിശോധന ആവശ്യമാണ്', secondaryInspection:'ദ്വിതീയ പരിശോധന ശുപാർശ ചെയ്യുന്നു', extractedDocumentInformation:'ലഭിച്ച രേഖാ വിവരങ്ങൾ', fullName:'പേര്', documentType:'രേഖ തരം', documentNumber:'രേഖാ നമ്പർ', nationality:'ദേശീയത', dateOfBirth:'ജനന തീയതി', expiryDate:'കാലഹരണ തീയതി', notAvailable:'ലഭ്യമല്ല', documentIntegrity:'രേഖയുടെ സമഗ്രത', faceVerification:'മുഖ പരിശോധന', faceMatch:'മുഖ പൊരുത്തം', match:'പൊരുത്തം', mismatch:'പൊരുത്തമില്ല', reasons:'കാരണങ്ങൾ', recommendation:'ശുപാർശ', reason_name_region_anomaly:'പേര് മേഖലയ്ക്ക് സമീപം സാധ്യതയുള്ള മാറ്റം കണ്ടെത്തി.', reason_visible_mrz_data_mismatch:'കോഡ് ചെയ്ത വിവരങ്ങൾ ദൃശ്യമാകുന്ന വാചകവുമായി പൊരുത്തപ്പെടുന്നില്ല.', reason_face_mismatch:'രേഖാചിത്രവും സെൽഫിയും തമ്മിൽ മുഖം പൊരുത്തപ്പെടുന്നില്ല.', reason_low_image_quality:'കുറഞ്ഞ ചിത്ര നിലവാരം പരിശോധനയെ ബാധിക്കാം.', reason_typography_inconsistency:'രേഖയിൽ അക്ഷരവിന്യാസത്തിലെ പൊരുത്തക്കേട് കണ്ടെത്തി.' },
  bn: { language:'ভাষা', screening:'নথি যাচাই', identityScreening:'পরিচয় যাচাই', identityDocument:'পরিচয় নথি', applicantSelfie:'আবেদনকারীর সেলফি', uploadIdentityDocument:'পরিচয় নথি আপলোড করুন', dragDrop:'টেনে ছেড়ে দিন', clickToUpload:'আপলোড করতে ক্লিক করুন', browseFile:'ফাইল নির্বাচন করুন', startAnalysis:'বিশ্লেষণ শুরু করুন', startScreening:'পরিচয় যাচাই শুরু করুন', processing:'যাচাই চলছে…', newScreening:'নতুন যাচাই', verificationResult:'যাচাইকরণের ফলাফল', riskScore:'ঝুঁকি স্কোর', riskAssessment:'ঝুঁকি মূল্যায়ন', lowRisk:'কম ঝুঁকি', mediumRisk:'মাঝারি ঝুঁকি', highRisk:'উচ্চ ঝুঁকি', manualReviewRequired:'ম্যানুয়াল পর্যালোচনা প্রয়োজন', secondaryInspection:'দ্বিতীয় পরিদর্শন সুপারিশ করা হয়েছে', extractedDocumentInformation:'প্রাপ্ত নথির তথ্য', fullName:'নাম', documentType:'নথির ধরন', documentNumber:'নথি নম্বর', nationality:'জাতীয়তা', dateOfBirth:'জন্ম তারিখ', expiryDate:'মেয়াদ শেষের তারিখ', notAvailable:'উপলব্ধ নয়', documentIntegrity:'নথির অখণ্ডতা', faceVerification:'মুখ যাচাইকরণ', faceMatch:'মুখের মিল', match:'মিল', mismatch:'অমিল', reasons:'কারণ', recommendation:'সুপারিশ', reason_name_region_anomaly:'নাম ক্ষেত্রের আশেপাশে সম্ভাব্য পরিবর্তন শনাক্ত হয়েছে।', reason_visible_mrz_data_mismatch:'এনকোড করা তথ্য দৃশ্যমান লেখার সঙ্গে মেলে না।', reason_face_mismatch:'নথির ছবি ও সেলফির মধ্যে মুখের অমিল শনাক্ত হয়েছে।', reason_low_image_quality:'কম ছবির গুণমান যাচাইকরণে প্রভাব ফেলতে পারে।', reason_typography_inconsistency:'নথিতে টাইপোগ্রাফির অসঙ্গতি শনাক্ত হয়েছে।' },
  mr: { language:'भाषा', screening:'दस्तऐवज तपासणी', identityScreening:'ओळख तपासणी', identityDocument:'ओळख दस्तऐवज', applicantSelfie:'अर्जदाराचा सेल्फी', uploadIdentityDocument:'ओळख दस्तऐवज अपलोड करा', dragDrop:'ड्रॅग आणि ड्रॉप करा', clickToUpload:'अपलोड करण्यासाठी क्लिक करा', browseFile:'फाइल निवडा', startAnalysis:'विश्लेषण सुरू करा', startScreening:'ओळख तपासणी सुरू करा', processing:'तपासणी सुरू आहे…', newScreening:'नवीन तपासणी', verificationResult:'पडताळणी निकाल', riskScore:'जोखीम गुण', riskAssessment:'जोखीम मूल्यांकन', lowRisk:'कमी जोखीम', mediumRisk:'मध्यम जोखीम', highRisk:'उच्च जोखीम', manualReviewRequired:'हस्तचालित पुनरावलोकन आवश्यक', secondaryInspection:'दुय्यम तपासणीची शिफारस', extractedDocumentInformation:'मिळालेली दस्तऐवज माहिती', fullName:'नाव', documentType:'दस्तऐवज प्रकार', documentNumber:'दस्तऐवज क्रमांक', nationality:'राष्ट्रीयत्व', dateOfBirth:'जन्मतारीख', expiryDate:'कालबाह्यता तारीख', notAvailable:'उपलब्ध नाही', documentIntegrity:'दस्तऐवज अखंडता', faceVerification:'चेहरा पडताळणी', faceMatch:'चेहरा जुळणी', match:'जुळणी', mismatch:'न जुळणे', reasons:'कारणे', recommendation:'शिफारस', reason_name_region_anomaly:'नावाच्या क्षेत्राभोवती संभाव्य बदल आढळला.', reason_visible_mrz_data_mismatch:'संकेतबद्ध माहिती दृश्य मजकुराशी जुळत नाही.', reason_face_mismatch:'दस्तऐवजातील प्रतिमा आणि सेल्फीमध्ये चेहरा जुळत नाही.', reason_low_image_quality:'कमी प्रतिमा गुणवत्ता पडताळणीवर परिणाम करू शकते.', reason_typography_inconsistency:'दस्तऐवजात टायपोग्राफी विसंगती आढळली.' },
}

const Context = createContext(null)
export function I18nProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('preferredLanguage') || 'en')
  useEffect(() => { localStorage.setItem('preferredLanguage', language); document.documentElement.lang = language }, [language])
  const value = useMemo(() => ({ language, setLanguage, t: (key) => localized[language]?.[key] || en[key] || key }), [language])
  return <Context.Provider value={value}>{children}</Context.Provider>
}
export function useTranslation() { return useContext(Context) }

const REASON_KEYS = ['NAME_REGION_ANOMALY', 'VISIBLE_MRZ_DATA_MISMATCH', 'FACE_MISMATCH', 'LOW_IMAGE_QUALITY', 'TYPOGRAPHY_INCONSISTENCY']
export function translateReason(reason, t) {
  if (typeof reason !== 'string') return reason
  const code = REASON_KEYS.find((item) => reason.toUpperCase().includes(item))
  return code ? t(`reason_${code.toLowerCase()}`) : reason
}
